export function getMarketName(marketCode: string): string {
  const marketMapping: Record<string, string> = {
    "KRW-BTC": "비트코인",
    "KRW-ETH": "이더리움",
    "KRW-XRP": "리플",
    "KRW-DOGE": "도지코인",
    "KRW-BTT": "비트토렌트",
    "KRW-VET": "비체인",
    "KRW-CHZ": "칠리즈",
    "KRW-CRO": "크로노스",
    "KRW-SAND": "샌드박스",
    "KRW-ADA": "에이다",
    "KRW-DOT": "폴카닷",
    "KRW-TRX": "트론",
    "KRW-SOL": "솔라나",
    "KRW-MANA": "디센트럴랜드",
    "KRW-AVAX": "아발란체",
    "KRW-ATOM": "코스모스",
    "KRW-NEO": "네오",
    "KRW-BCH": "비트코인 캐시",
    "KRW-ICX": "아이콘",
    "KRW-ETC": "이더리움 클래식",
    "KRW-ZIL": "질리카",
    "KRW-ONT": "온톨로지",
    "KRW-HBAR": "헤데라 해시그래프",
    "KRW-KLAY": "클레이튼",
    "KRW-EOS": "이오스",
    "KRW-STX": "스택스",
    "KRW-ALGO": "알고랜드",
    "KRW-FTM": "팬텀",
    "KRW-GRT": "그래프",
    "KRW-THETA": "쎄타",
    "KRW-FLOW": "플로우",
    "KRW-AAVE": "아베",
    "KRW-BNB": "바이낸스 코인",
    "KRW-MKR": "메이커",
    "KRW-SNX": "신세틱스",
    "KRW-YFI": "연파이낸스",
    "KRW-ZRX": "제로엑스",
    "KRW-UNI": "유니스왑",
    "KRW-LINK": "체인링크",
    "KRW-COMP": "컴파운드",
    "KRW-CRV": "커브",
    "KRW-SUSHI": "스시스왑",
    "KRW-REN": "렌",
    "KRW-MIR": "미러 프로토콜",
    "KRW-ANKR": "앵커",
    "KRW-1INCH": "1인치",
    "KRW-RLC": "아이젝",
    "KRW-TON": "톤코인",
    "KRW-VGX": "보이저 토큰",
  };

  return marketMapping[marketCode] || "알 수 없음";
}
